### ISSUE TITLE
Question - Where is Ipopt in Docker?

### ISSUE THREAD

**Issue by CollopCan** [mbonvini/JModelicaDemo#5]
Hi,
I appreciate your Dockerfile. I followed it and successfully compiled Ipopt. But I couldn't find the executable. I was trying to call Ipopt with Pyomo, like: 
solver = SolverFactory ('ipopt',executable = opt_dir)
What should I put at 'opt_dir'?

Thank you in advance.

**Comment by mbonvini** [comment]
Hi

it never happen to directly use the executable... but I looked around quickly and there is this folder `/home/docker/installed/Ipopt` containing the dlls
```
docker@5b15f84d9e8e:~/installed/Ipopt$ tree -L 2
.
|-- include
|   `-- coin
|-- lib
|   |-- libcoinblas.la
|   |-- libcoinblas.so -> libcoinblas.so.1.4.4
|   |-- libcoinblas.so.1 -> libcoinblas.so.1.4.4
|   |-- libcoinblas.so.1.4.4
|   |-- libcoinlapack.la
|   |-- libcoinlapack.so -> libcoinlapack.so.1.5.4
|   |-- libcoinlapack.so.1 -> libcoinlapack.so.1.5.4
|   |-- libcoinlapack.so.1.5.4
|   |-- libcoinmetis.la
|   |-- libcoinmetis.so -> libcoinmetis.so.1.3.4
|   |-- libcoinmetis.so.1 -> libcoinmetis.so.1.3.4
|   |-- libcoinmetis.so.1.3.4
|   |-- libcoinmumps.la
|   |-- libcoinmumps.so -> libcoinmumps.so.1.5.4
|   |-- libcoinmumps.so.1 -> libcoinmumps.so.1.5.4
|   |-- libcoinmumps.so.1.5.4
|   |-- libipopt.la
|   |-- libipopt.so -> libipopt.so.1.10.4
|   |-- libipopt.so.1 -> libipopt.so.1.10.4
|   |-- libipopt.so.1.10.4
|   `-- pkgconfig
`-- share
    `-- coin
```

If that's not what you need, I suggest you to look at Ipopt's documentation, keeping in mind that here is how it is installed.

https://github.com/mbonvini/ModelicaInAction/blob/1e6c21975f96e8539419d54c42fcfb9db6a3e039/docker/Dockerfile#L51-L71

Hope it helps,
Marco

**Comment by nthanapaisal** [comment]
Hi,

I am encountering an issue with the example on how to install ipopt using dockerfile. Here's a backstory, so I noticed that when I tried to run my application inside my docker container. I noticed that the library I use "Casadi" threw an error (even thought the app works in my local machine (MacOS).

`  File "/opt/conda/lib/python3.9/site-packages/casadi/casadi.py", line 28924, in nlpsol
    return _casadi.nlpsol(*args)
RuntimeError: .../casadi/core/plugin_interface.hpp:292: Plugin 'ipopt' is not found.`

I also read somewhere from the documentation that because of this: this is could be why I got the error. 
`Note that if you use the prebuilt CasADi binaries for Windows or Linux, IPOPT is included and does not need to be installed separately.`


So I have tried to install ipopt using Dockerfile for container and I got this error when it was running this line:

```
Dockerfile:40
--------------------
  38 |     RUN ./get.Lapack
  39 |     WORKDIR $LIB_DIR/docker/to_install/Ipopt/Ipopt-3.12.4/ThirdParty/Mumps
  40 | >>> RUN ./get.Mumps
  41 |     WORKDIR $LIB_DIR/docker/to_install/Ipopt/Ipopt-3.12.4/ThirdParty/Metis
  42 |     RUN ./get.Metis
--------------------
ERROR: failed to solve: process "/bin/sh -c ./get.Mumps" did not complete successfully: exit code: 4
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c ./get.Mumps" did not complete successfully: exit code: 4
```

I however not sure what is why with **./get.Mumps** I wonder if you could help?

Thanks
